version: "3.0"

services:
  service:
    image: git-service:latest
    restart: always
    depends_on:
      - db
    ports:
      - 4005:4005
    expose:
      - "4005"
    build: ./
    volumes:
      - ./:/project
    environment:
      DOCKER_DB_URL: postgresql://user:password@db:5432/git-service
    tty: true

  db:
    image: postgres:13.7-bullseye
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: git-service
    volumes:
      - db-data:/db-data/

volumes:
  db-data:
